# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "tty-table", "~> 0.12.0"

gem "pastel", "~> 0.8.0"

gem "colorize", "~> 0.8.1"

gem "rspec", "~> 3.10"

gem "tty-prompt", "~> 0.23.1"
